[theme]
# Tema personalizado para o dashboard Chatvolt
primaryColor = "#3498db"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
# Configurações do servidor
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Configurações do browser
gatherUsageStats = false

[global]
# Configurações globais
developmentMode = false
showWarningOnDirectExecution = false
